sudo: false
language: ruby
services:
  - docker
rvm:
  - 2.7.0
before_install: gem install bundler -v 2.0.2
script: >
  bundle exec rake &&
  bundle exec rubocop &&
  bundle exec fasterer &&
  docker build -t bakery .
