name: Docker Image CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag bakery:$(date +%s)
      - name: Hadolint Action
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
