name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.7.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Build and test with Rake, RSpec, RuboCop, Fasterer
      run: |
        gem install bundler -v 2.0.2
        bundle install --jobs 4 --retry 3
        bundle exec rake
        bundle exec rubocop
        bundle exec fasterer
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: bundle exec rake
        debug: true
