name: Ruby

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Lint code for consistent style with RuboCop
        run: bin/rubocop --parallel -f github
        continue-on-error: true
      - name: Use Fasterer to check various places in your code that could be faster.
        run: bin/fasterer
        continue-on-error: true
      - name: Build and test with Rake, RSpec
        run: bin/rake
        continue-on-error: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
