name: Ruby

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Build and test with Rake, RSpec, RuboCop, Fasterer
        run: |
          bin/rake
          bin/rubocop
          bin/fasterer
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
